### PR TITLE
Building atoms

### PR DESCRIPTION
**Pull request by atwfk**
###Description

-created atoms:-
               -colors
               -styles
               -typography
               -icons
               -tabs
               -buttons
               -forms
               -toggles
               -checkboxes
               -radios

-moved colors, styles, typography and tabs to gallery.html

-fixed a bug: (showing icons when focus on inputs with left icon)

-fixed a syntax error in index.html on line 3848

-fixed a warning: (the two classes(pointer-events-none, opacity-50) wrote twice on the same element)

### CODE REVIEW

**Comment by eslamheshamm** [comment]
Nice Work, Ahmed!
But consider:
- Be more descriptive in the title
- Your description should be clear and describe what you've done in main points
- Disabled Buttons shouldn't have a focus when clicked
- Buttons focus should be smaller

**Review by eslamheshamm — COMMENTED** [review]
Nice Work, Ahmed!
But consider:
- Be more descriptive in the title
- Your description should be clear and describe what you've done in main points
- Disabled Buttons shouldn't have a focus when clicked
- Buttons focus should be smaller

**Comment by atwfk** [comment]
> Nice Work, Ahmed!
> But consider:
> 
> * Be more descriptive in the title
> * Your description should be clear and describe what you've done in main points
> * Disabled Buttons shouldn't have a focus when clicked
> * Buttons focus should be smaller

-adding pointer-events-none on disabled buttons and inputs to prevent clicking
-adding smaller borders on button focus

**Review by eslamheshamm — APPROVED** [review]
LGTM

**Review by eslamheshamm — APPROVED** [review]

**Pull request merged**
